added install dm

diff --git a/RiceInstaller b/RiceInstaller
--- a/RiceInstaller
+++ b/RiceInstaller
@@ -72,39 +72,6 @@ based_update() {
     sudo pacman -Syu --noconfirm
 }
 
-# Install based driver
-based_install() {    
-    # video driver
-    clear
-    logo "Install video driver"
-    
-    echo "Driver Installation"
-    echo "1) VirtualBox"
-    echo "2) Intel / AMD / NVIDIA GPU (bare metal)"
-    echo "3) Skip this step"
-    read -rp "Choose an option [1-3]: " x_choice
-
-
-    case "$x_choice" in
-        1)
-            echo ">> Installing VirtualBox guest drivers"
-            sudo pacman -S --noconfirm  virtualbox-guest-utils xf86-video-vesa || log_error "Failed to install VirtualBox drivers"
-            systemctl enable vboxservice.service
-            ;;
-        2)
-            echo ">> Installing X server and generic GPU drivers..."
-            sudo pacman -S --noconfirm xf86-video-vesa || log_error "Failed to install X and GPU drivers"
-            ;;
-        3)
-            echo ">> Skipping X driver installation."
-            return
-            ;;
-        *)
-            echo "Invalid choice. Skipping."
-            ;;
-    esac
-}
-
 # Verificaciones iniciales
 initial_checks() {
     # Verificar usuario root
@@ -878,20 +845,32 @@ final_prompt() {
     done
 }
 
-based_x_install()  {
-    # x config
+install_displaymanager_dependencies() {
     clear
-    logo "Install X server"
-    
-    sudo pacman -S xorg-server xorg-xinit --noconfirm || log_error "Failed to install X server (xorg-server xorg-xinit)"
-    $config="$HOME/dotfiles/d-config/xconfig/.xinitrc"
+    logo "Installing needed packages repository..."
+    sleep 2
 
-    cp $config "$HOME" || log_error "Failed to copy config X server ($HOME/dotfiles/d-config/xconfig/.xinitrc to $HOME)"
-}
+    # List of dependencies
+    gh0stzk_dependencies="lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings"
+
+    printf "%b\n\n" "${BLD}${CBL}Checking for required packages...${CNC}"
+    sleep 2
+
+    # Detect missing packages
+    missing_gh0stzk_pkgs=""
+    for pkg in $gh0stzk_dependencies; do
+        if ! is_installed "$pkg"; then
+            missing_gh0stzk_pkgs="$missing_gh0stzk_pkgs $pkg"
+            printf "%b\n" " ${BLD}${CYE}$pkg ${CRE}not installed${CNC}"
+        else
+            printf "%b\n" "${BLD}${CGR}$pkg ${CBL}already installed${CNC}"
+        fi
+    done
+
+    sudo systemctl enable lightdm.service
 
 # --- Main run --- #
 based_update
-based_install
 initial_checks
 welcome
 add_gh0stzk_repo
@@ -907,5 +886,5 @@ backup_existing_config
 install_dotfiles
 configure_services
 change_default_shell
+install_displaymanager_dependencies
 final_prompt
-based_x_install
